/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS_PBO_06869;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Acer
 */
public class Fpelanggan extends javax.swing.JFrame {
    Boolean koreksi=false;
    public String tombol;
    public boolean databaru = false;
    public boolean data = false;
    /**
     * Creates new form Fpelanggan
     */
    public Fpelanggan() {
        initComponents();
        load_table();
        aktif(false);
        cmdTambah.requestFocus();         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKdpelanggan = new javax.swing.JTextField();
        txtNamapelanggan = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        cmdTambah = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();
        cmdKoreksi = new javax.swing.JButton();
        cmdCari = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdSelesai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("FORM ISI DATA PELANGGAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 380, 28);

        jLabel2.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel2.setText("KODE PELANGGAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 140, 30);

        jLabel3.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel3.setText("NAMA PELANGGAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 160, 30);

        jLabel4.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel4.setText("ALAMAT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 90, 30);

        jLabel5.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel5.setText("TELEPON");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 200, 70, 30);

        txtKdpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKdpelangganActionPerformed(evt);
            }
        });
        getContentPane().add(txtKdpelanggan);
        txtKdpelanggan.setBounds(180, 80, 140, 30);
        getContentPane().add(txtNamapelanggan);
        txtNamapelanggan.setBounds(180, 120, 140, 30);
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(180, 160, 140, 30);
        getContentPane().add(txtTelepon);
        txtTelepon.setBounds(180, 200, 140, 30);

        cmdTambah.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });
        getContentPane().add(cmdTambah);
        cmdTambah.setBounds(10, 260, 100, 27);

        cmdSimpan.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(cmdSimpan);
        cmdSimpan.setBounds(120, 260, 80, 27);

        cmdKoreksi.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        cmdKoreksi.setText("Koreksi");
        getContentPane().add(cmdKoreksi);
        cmdKoreksi.setBounds(220, 260, 90, 27);

        cmdCari.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        cmdCari.setText("Cari");
        cmdCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCariActionPerformed(evt);
            }
        });
        getContentPane().add(cmdCari);
        cmdCari.setBounds(410, 80, 59, 27);

        cmdHapus.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        cmdHapus.setText("Hapus");
        getContentPane().add(cmdHapus);
        cmdHapus.setBounds(330, 260, 73, 27);

        cmdSelesai.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        cmdSelesai.setText("Selesai");
        cmdSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(cmdSelesai);
        cmdSelesai.setBounds(420, 260, 90, 27);

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabeldata);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 300, 500, 150);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 204, 255));
        jLabel6.setText("Ryan Atha Muyassar");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 470, 300, 29);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 204, 255));
        jLabel7.setText("A12.2022.06869");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 500, 130, 40);

        setBounds(0, 0, 546, 585);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        String tkdpelanggan = txtKdpelanggan.getText();
        String tnamapelanggan = txtNamapelanggan.getText();
        String talamat = txtAlamat.getText();
        String tTelepon = txtTelepon.getText();
        
        if ("Tambah".equals(tombol) && databaru) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://"+"127.0.0.1/projekuas","root","");
                String sqlb = "INSERT INTO pelanggan VALUES('" + tkdpelanggan + "','" + tnamapelanggan + "','" + talamat + "','" + tTelepon + "')";
                PreparedStatement pst = conn.prepareStatement(sqlb);
                pst.execute();
                load_table();
                JOptionPane.showMessageDialog(null, "Data Tersimpan");
                databaru = false;
                txtKdpelanggan.setText("");
                txtNamapelanggan.setText("");
                txtAlamat.setText("");
                txtTelepon.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Tersimpan");
            }
        } else if ("Tambah".equals(tombol)) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://"+"127.0.0.1/projekuas","root","");
                String sqlb = "INSERT INTO pelanggan VALUES('" + tkdpelanggan + "','" + tnamapelanggan + "','" + talamat + "','" + tTelepon + "')";
                PreparedStatement pst = conn.prepareStatement(sqlb);
                pst.execute();
                load_table();
                JOptionPane.showMessageDialog(null, "Data Tersimpan");
                databaru = false;
                txtKdpelanggan.setText("");
                txtNamapelanggan.setText("");
                txtAlamat.setText("");
                txtTelepon.setText(""); 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Tersimpan");
            }
        }else if ("Koreksi".equals(tombol)) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://"+"127.0.0.1/projekuas","root","");
                String sqlb = "UPDATE pelanggan SET kdpelanggan='" + tkdpelanggan + "', nama_pelanggan='" + tnamapelanggan + "', alamat='" + talamat + "', telepon='" + tTelepon + "' WHERE kdpelanggan='" + tkdpelanggan + "'";
                PreparedStatement pst = conn.prepareStatement(sqlb);
                pst.execute();
                load_table();
                JOptionPane.showMessageDialog(null, "Data Terkoreksi");
                txtKdpelanggan.setText("");
                txtNamapelanggan.setText("");
                txtAlamat.setText("");
                txtTelepon.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Terkoreksi");
            } 
        } else if ("Hapus".equals(tombol)) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://"+"127.0.0.1/projekuas","root","");
                String sqlb = "DELETE FROM pelanggan WHERE kdpelanggan='" + tkdpelanggan + "'";
                PreparedStatement pst = conn.prepareStatement(sqlb);
                pst.execute();
                load_table();
                JOptionPane.showMessageDialog(null, "Data Terhapus");
                txtKdpelanggan.setText("");
                txtNamapelanggan.setText("");
                txtAlamat.setText("");
                txtTelepon.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Terhapus");
            }
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdSimpanActionPerformed

    private void txtKdpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKdpelangganActionPerformed
        String kdpelanggan = txtKdpelanggan.getText().trim(); 
        
        if (kdpelanggan.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Barang tidak boleh kosong");
            txtKdpelanggan.requestFocus();
            return;
        }

        String sql = "SELECT COUNT(*) AS count FROM pelanggan WHERE kdpelanggan = ?";
        try (Connection conn = Koneksi.configDB();
            PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, kdpelanggan);
            try (java.sql.ResultSet res = pstmt.executeQuery()) {
                System.out.println("Query executed: " + sql);
                if (res.next()) {
                    int count = res.getInt("count");
                    System.out.println("Count retrieved: " + count);
                    if (count > 0){
                        // Jika kode barang sudah ada, tampilkan pesan peringatan
                        JOptionPane.showMessageDialog(null, "Kode Pelanggan " + kdpelanggan + " sudah ada dalam database.");
                    } else {
                        // Jika kode barang belum ada, lakukan tindakan yang sesuai
                        JOptionPane.showMessageDialog(null, "Kode Pelanggan " + kdpelanggan + " belum ada dalam database, Anda dapat melanjutkan.");
                        databaru = true;
                    } 
                } else {
                    // Handling case if no result is returned
                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mendapatkan hasil dari database.");
                }                    
            }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengakses database: " + e.getMessage());
                e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        }              // TODO add your handling code here:
    }//GEN-LAST:event_txtKdpelangganActionPerformed

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        tombol = "Tambah";
        aktif(true);
        txtKdpelanggan.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSelesaiActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cmdSelesaiActionPerformed

    private void cmdCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCariActionPerformed
        aktif(true);
        tombol = "Cari";
        txtKdpelanggan.requestFocus();
        String kode = txtKdpelanggan.getText().trim();

        // Periksa apakah kode pelanggan tidak kosong
        if (kode.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Pelanggan tidak boleh kosong");
            txtKdpelanggan.requestFocus();
            return;
        }

        String sql = "SELECT * FROM pelanggan WHERE kdpelanggan='"+txtKdpelanggan.getText()+"'";
        try (java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        java.sql.Statement stm=conn.createStatement()) {
            
        try (java.sql.ResultSet res = stm.executeQuery(sql)) {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Kode Pelanggan");               
            model.addColumn("Nama Pelanggan");
            model.addColumn("Alamat");
            model.addColumn("Telepon");

            boolean found = false;
            while (res.next()) {
                found = true;
                model.addRow(new Object[]{                
                    res.getString("kdpelanggan"),
                    res.getString("nama_pelanggan"),
                    res.getString("alamat"),
                    res.getString("telepon"),
                    });
                }

                tabeldata.setModel(model);

                if (found) {
                    JOptionPane.showMessageDialog(null, "Data " + txtKdpelanggan.getText() + " berhasil ditemukan");
                } else {
                    JOptionPane.showMessageDialog(null, "Data " + txtKdpelanggan.getText() + " tidak ditemukan");
                }
            
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengakses database: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmdCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fpelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fpelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fpelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fpelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fpelanggan().setVisible(true);
            }
        });
    }
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Pelanggan");
        model.addColumn("Nama Pelanggan");
        model.addColumn("Alamat");
        model.addColumn("Telepon"); 
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://"+"127.0.0.1/projekuas","root","");
            String sql = "SELECT * FROM pelanggan";
            PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet res = pst.executeQuery();
            while(res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
            }
            tabeldata.setModel(model);
            conn.close();
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        }  
    }
    
    private void kosong(){
        txtKdpelanggan.setText(null);
        txtNamapelanggan.setText(null);
        txtAlamat.setText(null);
        txtTelepon.setText(null);      
    }

    private void aktif (boolean b){
        txtKdpelanggan.setEnabled(b);
        txtNamapelanggan.setEnabled(b);
        txtAlamat.setEnabled(b);
        txtTelepon.setEnabled(b);        
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCari;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdKoreksi;
    private javax.swing.JButton cmdSelesai;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabeldata;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtKdpelanggan;
    private javax.swing.JTextField txtNamapelanggan;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
