/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS_PBO_06869;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class Fuser01 extends javax.swing.JFrame {
    Statement stm;
    public String tombol;

    /**
     * Creates new form Data_Barang
     */
    public Fuser01() {
        initComponents();
        load_table();
        aktif(false);
        cmdTambah.requestFocus();        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUserid = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        dtTanggalbuat = new com.toedter.calendar.JDateChooser();
        cmdTambah = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();
        cmdKoreksi = new javax.swing.JButton();
        cmdCari = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdSelesai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabeldata = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("FORM USER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 160, 28);

        jLabel2.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel2.setText("USER ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 90, 33);

        jLabel3.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel3.setText("NAMA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 100, 33);

        jLabel4.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel4.setText("PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 170, 110, 33);

        jLabel5.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel5.setText("TANGGAL BUAT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 220, 120, 16);

        txtUserid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUseridKeyPressed(evt);
            }
        });
        getContentPane().add(txtUserid);
        txtUserid.setBounds(160, 70, 90, 25);
        getContentPane().add(txtNama);
        txtNama.setBounds(160, 120, 170, 30);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(160, 170, 170, 30);
        getContentPane().add(dtTanggalbuat);
        dtTanggalbuat.setBounds(160, 220, 170, 30);

        cmdTambah.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });
        getContentPane().add(cmdTambah);
        cmdTambah.setBounds(40, 280, 100, 27);

        cmdSimpan.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(cmdSimpan);
        cmdSimpan.setBounds(150, 280, 80, 27);

        cmdKoreksi.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        cmdKoreksi.setText("Koreksi");
        cmdKoreksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKoreksiActionPerformed(evt);
            }
        });
        getContentPane().add(cmdKoreksi);
        cmdKoreksi.setBounds(240, 280, 90, 27);

        cmdCari.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        cmdCari.setText("Cari");
        cmdCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCariActionPerformed(evt);
            }
        });
        getContentPane().add(cmdCari);
        cmdCari.setBounds(430, 70, 59, 27);

        cmdHapus.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });
        getContentPane().add(cmdHapus);
        cmdHapus.setBounds(340, 280, 73, 27);

        cmdSelesai.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        cmdSelesai.setText("Selesai");
        cmdSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(cmdSelesai);
        cmdSelesai.setBounds(420, 280, 80, 27);

        Tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabeldata);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(42, 320, 460, 180);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 204, 255));
        jLabel6.setText("Ryan Atha Muyassar");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 510, 300, 29);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 204, 255));
        jLabel7.setText("A12.2022.06869");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 540, 130, 40);

        setBounds(0, 0, 552, 615);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        String tuserid=txtUserid.getText();  
        String tnamauser=txtNama.getText();
        String tpassword=txtPassword.getText(); 
    
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggalBuat;
        tanggalBuat = String.valueOf(fm.format(dtTanggalbuat.getDate()));
        
        if (tombol=="Tambah"){
        try {
            String sqlb = "INSERT INTO user VALUES ('"+txtUserid.getText()+"','"+txtNama.getText()+"','"+txtPassword.getText()+"','"+tanggalBuat+"')";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sqlb);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        
        if (tombol=="Koreksi"){
        try {
            String sqla= "UPDATE user SET nama_user='"+tnamauser+"',password='"+tpassword+"',tanggal_buat='"+tanggalBuat+"' where user_id='"+tuserid+"'";
            java.sql.Connection conn =(java.sql.Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sqla);
            pst.execute();
            JOptionPane.showMessageDialog(null, "berhasil disimpan");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        load_table();
      }	

 }

// TODO add your handling code here:
    }//GEN-LAST:event_cmdSimpanActionPerformed

    private void txtUseridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUseridKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn=DriverManager.getConnection("jdbc:mysql://"+"127.0.0.1/projekuas","root","");
            Statement stm=cn.createStatement(); 
        
        if (tombol=="Tambah"){
            if(txtUserid.getText().equals("")){
                JOptionPane.showMessageDialog(null,"User Id tidak boleh kosong","Validasis Data",JOptionPane.INFORMATION_MESSAGE);
                txtUserid.requestFocus();
                return;
            }
            if(!"".equals(txtUserid.getText())) {
                ResultSet rs = stm.executeQuery("Select * from user where user_id='" +txtUserid.getText() + "'");
                if (rs.next()) {
                    txtNama.setText(rs.getString("nama_user"));
                    txtPassword.setText(rs.getString("password"));
                    dtTanggalbuat.setDate(rs.getDate("tanggal_buat"));
                    JOptionPane.showMessageDialog(this,"Data Sudah Ada", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    kosong();
                    aktif(true);
                    txtUserid.requestFocus();
            } else {
                    txtNama.requestFocus();
                }  
            }
        }
        
            if (tombol=="Cari"){
            ResultSet rs = stm.executeQuery("Select * from user where user_id='" +txtUserid.getText() + "'");
                if (rs.next()) {
                    txtNama.setText(rs.getString("nama_user"));
                    txtPassword.setText(rs.getString("password"));
                    dtTanggalbuat.setDate(rs.getDate("tanggal_buat"));
                    JOptionPane.showMessageDialog(this,"Data ditemukan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    warna();
                    aktif(false);
                } else {
                    JOptionPane.showMessageDialog(this,"Data Tidak Ada", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    txtUserid.requestFocus();
                }
          }
         }catch(SQLException e){
        }   catch (ClassNotFoundException ex) {    
                Logger.getLogger(Fuser01.class.getName()).log(Level.SEVERE, null, ex);
        }
        }   
            // TODO add your handling code here:
    }//GEN-LAST:event_txtUseridKeyPressed

    private void cmdCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCariActionPerformed
        tombol="Cari";
        aktif(true);
        kosong();
        txtUserid.setText("");
        txtUserid.requestFocus();
            // TODO add your handling code here:
    }//GEN-LAST:event_cmdCariActionPerformed

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        tombol="Tambah";
        aktif(true);
        txtUserid.setText("");
        kosong();
        txtUserid.requestFocus();
            // TODO add your handling code here:
    }//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdKoreksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKoreksiActionPerformed
        tombol="Koreksi";
        aktif(true);
        txtNama.requestFocus();    
            // TODO add your handling code here:
    }//GEN-LAST:event_cmdKoreksiActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn=DriverManager.getConnection("jdbc:mysql://"+"127.0.0.1/projekuas","root","");
            Statement stm=cn.createStatement();    
            String sqlc="delete from user where user_id='"+txtUserid.getText() +"'";
            stm.executeUpdate(sqlc);
            load_table();
        } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Fuser01.class.getName()).log(Level.SEVERE, null, ex);
        }    
    // TODO add you r handling code here:
    }//GEN-LAST:event_cmdHapusActionPerformed

    private void cmdSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSelesaiActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cmdSelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fuser01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fuser01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fuser01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fuser01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fuser01().setVisible(true);
            }
        });
    }
    
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("User Id");
        model.addColumn("Nama");
        model.addColumn("Password");
        model.addColumn("Tanggal Buat");
        
        try {
            int no=1;
            String sql = "select * from user";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
            }
            Tabeldata.setModel(model);
        } catch (SQLException e) {
        }
    }
    
    private void kosong (){
        txtNama.setText(null);
        txtPassword.setText(null);
    }
    
    private void aktif(boolean b) {
        txtUserid.setEditable(b);
        txtNama.setEditable(b);
        txtPassword.setEditable(b);
        dtTanggalbuat.setEnabled(b);
    }
    
    private void warna(){
        txtUserid.setBackground(Color.YELLOW);
        txtNama.setBackground(Color.CYAN);
        txtPassword.setBackground(Color.CYAN);
        dtTanggalbuat.setBackground(Color.CYAN);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabeldata;
    private javax.swing.JButton cmdCari;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdKoreksi;
    private javax.swing.JButton cmdSelesai;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdTambah;
    private com.toedter.calendar.JDateChooser dtTanggalbuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserid;
    // End of variables declaration//GEN-END:variables
}
